In [2]:
import seaborn as sns
import string
import re
from collections import Counter
import matplotlib.pyplot as plt
import spacy
import en_core_web_sm
nlp = en_core_web_sm.load(disable=['parser','tagger','ner'])
import pandas as pd

In [15]:
import string
punctuations = string.punctuation
punctuations=punctuations+'—'+'–'+'--'

In [ ]:
# Creating our tokenizer function
def spacy_tokenizer(text):
    # Creating our token object, which is used to create documents with linguistic annotations.
    mytokens = parser(text)

    # Lemmatizing each token and converting each token into lowercase
    mytokens = [word.lemma_.lower().strip() if word.lemma_ !=
                "-PRON-" else word.lower_ for word in mytokens]

    # Removing stop words
    mytokens = [word for word in mytokens if word not in stop_words]
    
    #Removing punctuations
    mytokens = [word for word in mytokens if word not in punctuations]

    mytokens = ' '.join(mytokens)
    # return preprocessed list of tokens
    return mytokens

In [3]:
campaign_speeches=pd.read_csv('Campaign Speeches')

In [4]:
campaign_speeches.head()

candidate        date                                       speech title  \
0  Robert Dole  1995-04-10  Remarks Announcing Candidacy for the Republica...   
1  Robert Dole  1995-05-31         Remarks in Los Angeles: "Hollywood Speech"   
2  Robert Dole  1995-06-17  Remarks to the United States Conference of May...   
3  Robert Dole  1995-08-19             Remarks at the Iowa Straw Poll in Ames   
4  Robert Dole  1995-09-04  Remarks at the American Legion Convention in I...   

                                                text       party  \
0  Thank you, Governor Graves, Senator Kassebaum....  Republican   
1  I want to talk about a specific matter tonight...  Republican   
2  Thank you, Senator Kempthorne, and thank you a...  Republican   
3  Thank you, Dan Quayle , for that great introdu...  Republican   
4  Thank you, and thank you very much, Commander ...  Republican   

   won_nomination                                    sentiment_score  \
0               1  {'neg': 0.088, 'neu': 0.736, 'pos': 0.175, 'co...   
1               1  {'neg': 0.143, 'neu': 0.657, 'pos': 0.2, 'comp...   
2               1  {'neg': 0.12, 'neu': 0.711, 'pos': 0.17, 'comp...   
3               1  {'neg': 0.103, 'neu': 0.717, 'pos': 0.181, 'co...   
4               1  {'neg': 0.103, 'neu': 0.725, 'pos': 0.172, 'co...   

   positive  negative  
0     0.175     0.088  
1     0.200     0.143  
2     0.170     0.120  
3     0.181     0.103  
4     0.172     0.103

In [5]:
campaign_speeches=campaign_speeches.dropna(subset=['text'])

In [6]:
campaign_speeches.shape

(1691, 9)

In [81]:
obama_speeches=pd.read_csv('Obama Speeches')

In [103]:
len(obama_speeches)

519

In [8]:
nlp.max_length=100000000

In [9]:
party_speeches = campaign_speeches[(campaign_speeches.party == 'Democrat') & (campaign_speeches.won_nomination == 1)].reset_index(drop=True)

In [104]:
obama_text = [text for text in obama_speeches.text[0:100]]
obama_text = ' '.join(obama_text).strip()

In [19]:
def separate_punc(doc_text):
    return [token.text.lower() for token in nlp(doc_text) if token.text not in punctuations]

In [105]:
tokens = separate_punc(obama_text)

In [106]:
tokens

['on',
 'behalf',
 'of',
 'the',
 'great',
 'state',
 'of',
 'illinois',
 'crossroads',
 'of',
 'a',
 'nation',
 'land',
 'of',
 'lincoln',
 'let',
 'me',
 'express',
 'my',
 'deep',
 'gratitude',
 'for',
 'the',
 'privilege',
 'of',
 'addressing',
 'this',
 'convention',
 'tonight',
 'is',
 'a',
 'particular',
 'honor',
 'for',
 'me',
 'because',
 'let',
 "'s",
 'face',
 'it',
 'my',
 'presence',
 'on',
 'this',
 'stage',
 'is',
 'pretty',
 'unlikely',
 'my',
 'father',
 'was',
 'a',
 'foreign',
 'student',
 'born',
 'and',
 'raised',
 'in',
 'a',
 'small',
 'village',
 'in',
 'kenya',
 'he',
 'grew',
 'up',
 'herding',
 'goats',
 'went',
 'to',
 'school',
 'in',
 'a',
 'tin',
 'roof',
 'shack',
 'his',
 'father',
 'my',
 'grandfather',
 'was',
 'a',
 'cook',
 'a',
 'domestic',
 'servant',
 'but',
 'my',
 'grandfather',
 'had',
 'larger',
 'dreams',
 'for',
 'his',
 'son',
 'through',
 'hard',
 'work',
 'and',
 'perseverance',
 'my',
 'father',
 'got',
 'a',
 'scholarship',
 'to',
 's

In [107]:
# organize into sequences of tokens
train_len = 25+1 # 50 training words , then one target word

# Empty list of sequences
text_sequences = []

for i in range(train_len, len(tokens)):
    
    # Grab train_len# amount of characters
    seq = tokens[i-train_len:i]
    
    # Add to list of sequences
    text_sequences.append(seq)

In [108]:
text_sequences

[['on',
  'behalf',
  'of',
  'the',
  'great',
  'state',
  'of',
  'illinois',
  'crossroads',
  'of',
  'a',
  'nation',
  'land',
  'of',
  'lincoln',
  'let',
  'me',
  'express',
  'my',
  'deep',
  'gratitude',
  'for',
  'the',
  'privilege',
  'of',
  'addressing'],
 ['behalf',
  'of',
  'the',
  'great',
  'state',
  'of',
  'illinois',
  'crossroads',
  'of',
  'a',
  'nation',
  'land',
  'of',
  'lincoln',
  'let',
  'me',
  'express',
  'my',
  'deep',
  'gratitude',
  'for',
  'the',
  'privilege',
  'of',
  'addressing',
  'this'],
 ['of',
  'the',
  'great',
  'state',
  'of',
  'illinois',
  'crossroads',
  'of',
  'a',
  'nation',
  'land',
  'of',
  'lincoln',
  'let',
  'me',
  'express',
  'my',
  'deep',
  'gratitude',
  'for',
  'the',
  'privilege',
  'of',
  'addressing',
  'this',
  'convention'],
 ['the',
  'great',
  'state',
  'of',
  'illinois',
  'crossroads',
  'of',
  'a',
  'nation',
  'land',
  'of',
  'lincoln',
  'let',
  'me',
  'express',
  'my',

In [12]:
from keras.preprocessing.text import Tokenizer

Using TensorFlow backend.


In [109]:
# integer encode sequences of words
tokenizer = Tokenizer()
tokenizer.fit_on_texts(text_sequences)
sequences = tokenizer.texts_to_sequences(text_sequences)

In [110]:
sequences[0]

[21,
 1385,
 5,
 1,
 204,
 227,
 5,
 427,
 4395,
 5,
 6,
 165,
 968,
 5,
 1795,
 133,
 76,
 2106,
 48,
 1885,
 5342,
 13,
 1,
 2558,
 5,
 3033]

In [111]:
tokenizer.index_word

{1: 'the',
 2: 'and',
 3: 'to',
 4: 'that',
 5: 'of',
 6: 'a',
 7: 'we',
 8: 'in',
 9: 'i',
 10: "'s",
 11: 'is',
 12: 'it',
 13: 'for',
 14: 'you',
 15: 'this',
 16: 'our',
 17: 'have',
 18: 'are',
 19: 'not',
 20: "n't",
 21: 'on',
 22: 'they',
 23: 'who',
 24: 'but',
 25: 'will',
 26: 'be',
 27: 'do',
 28: 'with',
 29: 'what',
 30: 'as',
 31: 'can',
 32: 'when',
 33: 'was',
 34: 'people',
 35: 'about',
 36: 'their',
 37: 'from',
 38: 'or',
 39: 'all',
 40: 'more',
 41: 'so',
 42: 'by',
 43: 'know',
 44: 'because',
 45: 'there',
 46: "'ve",
 47: 'if',
 48: 'my',
 49: 'has',
 50: 'at',
 51: "'re",
 52: 'america',
 53: 'us',
 54: 'time',
 55: 'he',
 56: 'up',
 57: 'been',
 58: 'an',
 59: 'country',
 60: 'american',
 61: 'president',
 62: 'think',
 63: 'just',
 64: 'one',
 65: 'out',
 66: 'going',
 67: 'war',
 68: 'them',
 69: 'obama',
 70: 'make',
 71: 'those',
 72: 'need',
 73: 'new',
 74: 'your',
 75: 'now',
 76: 'me',
 77: 'would',
 78: 'how',
 79: 'change',
 80: 'iraq',
 81: 'some'

In [112]:
tokenizer.word_counts

OrderedDict([('on', 49193),
             ('behalf', 522),
             ('of', 187076),
             ('the', 354324),
             ('great', 4945),
             ('state', 4530),
             ('illinois', 2348),
             ('crossroads', 87),
             ('a', 161991),
             ('nation', 6252),
             ('land', 871),
             ('lincoln', 379),
             ('let', 8128),
             ('me', 15071),
             ('express', 304),
             ('my', 23913),
             ('deep', 358),
             ('gratitude', 73),
             ('for', 85016),
             ('privilege', 232),
             ('addressing', 156),
             ('this', 70119),
             ('convention', 572),
             ('tonight', 1664),
             ('is', 88548),
             ('particular', 442),
             ('honor', 1092),
             ('because', 24362),
             ("'s", 98800),
             ('face', 4264),
             ('it', 87542),
             ('presence', 364),
             ('stage', 598),
 

In [113]:
vocabulary_size = len(tokenizer.word_counts)

In [114]:
vocabulary_size

10631

### Convert to Numpy Matrix


In [93]:
import numpy as np

In [115]:
sequences = np.array(sequences)

In [116]:
sequences

array([[  21, 1385,    5, ..., 2558,    5, 3033],
       [1385,    5,    1, ...,    5, 3033,   15],
       [   5,    1,  204, ..., 3033,   15, 1280],
       ...,
       [   4,   11,    1, ..., 2107,    1,  152],
       [  11,    1, 1579, ...,    1,  152,  124],
       [   1, 1579,    5, ...,  152,  124,    5]])

# Creating an LSTM based model


In [43]:
import keras
from keras.models import Sequential
from keras.layers import Dense,LSTM,Embedding

In [96]:
def create_model(vocabulary_size, seq_len):
    model = Sequential()
    model.add(Embedding(vocabulary_size, 25, input_length=seq_len))
    model.add(LSTM(150, return_sequences=True))
    model.add(LSTM(150))
    model.add(Dense(150, activation='relu'))
    model.add(Dropout(0.5))
    model.add(Dense(vocabulary_size, activation='softmax'))
    
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['categorical_accuracy'])
   
    model.summary()
    
    return model

### Train / Test Split

In [75]:
from keras.utils import to_categorical

In [117]:
sequences

array([[  21, 1385,    5, ..., 2558,    5, 3033],
       [1385,    5,    1, ...,    5, 3033,   15],
       [   5,    1,  204, ..., 3033,   15, 1280],
       ...,
       [   4,   11,    1, ..., 2107,    1,  152],
       [  11,    1, 1579, ...,    1,  152,  124],
       [   1, 1579,    5, ...,  152,  124,    5]])

In [118]:
# First 49 words
sequences[:,:-1]

array([[  21, 1385,    5, ...,    1, 2558,    5],
       [1385,    5,    1, ..., 2558,    5, 3033],
       [   5,    1,  204, ...,    5, 3033,   15],
       ...,
       [   4,   11,    1, ...,  426, 2107,    1],
       [  11,    1, 1579, ..., 2107,    1,  152],
       [   1, 1579,    5, ...,    1,  152,  124]])

In [119]:
# last Word
sequences[:,-1]

array([3033,   15, 1280, ...,  152,  124,    5])

In [120]:
X = sequences[:,:-1]

In [121]:
y = sequences[:,-1]

In [122]:
y = to_categorical(y, num_classes=vocabulary_size+1)

In [123]:
seq_len = X.shape[1]

In [124]:
seq_len

25

In [125]:
# define model
model = create_model(vocabulary_size+1, seq_len)

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_4 (Embedding)      (None, 25, 25)            265800    
_________________________________________________________________
lstm_5 (LSTM)                (None, 25, 150)           105600    
_________________________________________________________________
lstm_6 (LSTM)                (None, 150)               180600    
_________________________________________________________________
dense_5 (Dense)              (None, 150)               22650     
_________________________________________________________________
dense_6 (Dense)              (None, 10632)             1605432   
Total params: 2,180,082
Trainable params: 2,180,082
Non-trainable params: 0
_________________________________________________________________


In [126]:
from pickle import dump,load

In [129]:
X.shape

(303548, 25)

In [135]:
# fit model
model.fit(X, y, batch_size=300, epochs=10,verbose=1)

Epoch 1/10
303548/303548 [==============================] - 130s 429us/step - loss: 4.7015 - acc: 0.1761
Epoch 2/10
303548/303548 [==============================] - 130s 429us/step - loss: 4.6463 - acc: 0.1793
Epoch 3/10
303548/303548 [==============================] - 127s 418us/step - loss: 4.5905 - acc: 0.1828
Epoch 4/10
303548/303548 [==============================] - 123s 405us/step - loss: 4.5357 - acc: 0.1859
Epoch 5/10
303548/303548 [==============================] - 126s 414us/step - loss: 4.4828 - acc: 0.1891
Epoch 6/10
303548/303548 [==============================] - 125s 413us/step - loss: 4.4346 - acc: 0.1917
Epoch 7/10
303548/303548 [==============================] - 123s 407us/step - loss: 4.3872 - acc: 0.1950
Epoch 8/10
303548/303548 [==============================] - 121s 398us/step - loss: 4.3428 - acc: 0.1978
Epoch 9/10
303548/303548 [==============================] - 121s 399us/step - loss: 4.2997 - acc: 0.2009
Epoch 10/10
303548/303548 [============================